resolver 127.0.0.11 valid=5s;

server {
    listen 80;

    set $login_upstream http://login:8080;
    set $star_upstream http://star:8080;

    location /cs122b-project5-murphy-movies/api/login {
        proxy_pass $login_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Cookie $http_cookie;
    }

    location /cs122b-project5-murphy-movies/login.html {
        proxy_pass $login_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Cookie $http_cookie;
    }

    location /cs122b-project5-murphy-movies/login.js {
        proxy_pass $login_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Cookie $http_cookie;
    }

    location /cs122b-project5-murphy-movies/ {
        proxy_pass $star_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Cookie $http_cookie;
    }
}
